project:
  type: website
  output-dir: "docs"


website:
  title: "Jeff Wu"
  navbar:
    left:
      # - text: "Home"
      #   file: index.qmd
      - text: "Appendices"
        file: 4_onlineAppendices.qmd
      - text: "Portfolio"
        file: 3_portfolio.qmd
      - text: "Software"
        file: 2_software.qmd
      - text: "CV"
        file: 1_cv.qmd
    # right:
    #   - about.qmd
      # - icon: github
      #   href: https://github.com/
      # - icon: twitter
      #   href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css
editor: visual

