---
title: "My learning resources"
format: html
page-layout: full
title-block-banner: true
bibliography: references.bib
---

```{=html}
<script>
    // Encrypted password
    const passwordHash = "aea5a5ee6792fab36f3c60e62ef64e40061a8dac7d868b359aff7a4786a32e51";

    // Prompt user for the password
    const userInput = prompt("Password:");

    // Function to hash the user input
    async function hashInput(input) {
        const encoder = new TextEncoder();
        const data = encoder.encode(input);
        const hashBuffer = await crypto.subtle.digest("SHA-256", data);
        const hashArray = Array.from(new Uint8Array(hashBuffer));
        return hashArray.map(byte => byte.toString(16).padStart(2, '0')).join('');
    }

    // Verify the password
    hashInput(userInput).then(inputHash => {
        if (inputHash !== passwordHash) {
            document.body.innerHTML = "<h1>Access Denied</h1><p>You do not have the correct password to access this page.</p>";
        }
    });
</script>
```

# Microeconomics

@Varian2024: **Intermediate Microeconomics: A Modern Approach**

-   Chapter 5: Choices

    -   5.3 & 5.4 Demand functions and properties for Cobb-Douglas preferences

Jonathan Gruber (2018): **Principles of Microeconomics**

::: panel-tabset
## 5. Production theory

[5. Production theory](https://www.youtube.com/watch?v=ftmvsahQ6Wo&t=587s&ab_channel=MITOpenCourseWare)

\[9:20\] Marginal production of labour

-   "The diminishing marginal product of labour arises from the notion of short-run production constraints, where capital remains fixed."

\[18:13\] Marginal rate of technical substitution; \[25:03\] Return to scale; \[31:39\] Productivity.

## 6. Costs

\[9:13\] Cost function, marginal cost of production, \[41:00\] Long-run cost curve (expansion path)

-   \[13:40\] The marginal cost of production is related to the marginal production of labour through the wage rate.
-   \[32:55\] The cost function is derived from a production function, labour costs, and capital costs.
-   \[44:50\] Both the long-run and short-run cost curves are u-shape (see explanations and examples in @Varian2024, chapter 22)
:::

@Pollak1992: **Demand system specification & estimation**

-   Chapter 1: Linear Expenditure System (LES)
-   Chapter 2: Functional form specification
    -   2.1.1 Expenditure proportionality
    -   2.1.2 Demand systems linear in expenditure
-   Chapter 3: Demographic translating

------------------------------------------------------------------------

# Statistical modelling & econometrics

@Train2009: **Discrete Choice Methods with Simulation**

-   Chapter 2: Properties of discrete choice models
    -   2.3 Derivation of choice properties
-   Chapter 3: Logit
-   Chapter 4: GEV
-   Chapter 5: Probit

Paul Sweeting (2023): **Copluas**

-   [5 - Working with copulas in R](https://www.youtube.com/watch?v=XZcoA1rGbgE&ab_channel=PaulSweeting "The author's YouTube video.")

-   [3.1 - Choosing a copula](https://www.youtube.com/watch?v=XZcoA1rGbgE&ab_channel=PaulSweeting "The author's YouTube video.")

-   [2 - After the basics](https://www.youtube.com/watch?v=gzUxg0OUHU4&list=PLNt9IHkgoaro2jbfyd7QMa_FzL2vstco5&index=2&ab_channel=PaulSweeting "The author's YouTube video.")

    -   \[14:14\] From marginal distributions to a copula distribution
    -   \[18:28\] Building a normal copula by hand

Andreas Tilevik, 2021, [Generalised linear models (GLMs)](https://www.tilestats.com/videos/%7D)

-   [Quasi-Poisson, negative binomial](https://www.youtube.com/watch?v=jnKDQtDy0Bg&list=PLLTSM0eKjC2cYVUoex9WZpTEYyvw5buRc&index=13&ab_channel=TileStats)

Gavin Simpson, 2020, [Generalised additive models (GAM) with R and mgcv](https://www.youtube.com/watch?v=sgw4cu8hrZM&ab_channel=BottomoftheHeap)

-   Model (over-)fitting: Penalised log-likelihood

-   Smoothing: Basis functions, splines, interactions

------------------------------------------------------------------------

# Causal inference

Sant'Anna (2023), UMISR **Difference-in-differences**:

-   [Part 2](https://www.youtube.com/watch?v=R5dTf3n-_Rg&ab_channel=UMISR)
    -   \[14:14\] From marginal distributions to a copula distribution
    -   \[18:28\] Building a normal copula by hand
-   [Part 3](https://www.youtube.com/watch?v=mu9zRs7fUbk&ab_channel=UMISR): The interpretation of TWFE estimator when treatment effects are heterogeneous.
    -   \[30:30\] Bacon-decomposition of a TWFE estimator

Huntington-Klein (2022), [Staggered DiD: Addressing tension between the DiD concept and two-way fixed effects specification.](https://www.youtube.com/watch?v=hu2nDbnpALA&ab_channel=Econometrics%2CCausality%2CandCodingwithDr.HK)

-   Also refer to Alagoz (2023), [Staggered Difference-in-Differences in Practice](https://www.youtube.com/watch?v=rkP4TK1SPVQ&ab_channel=PyData), for a visual explanation.
-   \[9:45\] Early treated, late treated, never treated groups.

Matt Masten, 2015, Duke University Social Science Research Institute: [Causal Inference Bootcamp](https://mattmasten.github.io/bootcamp/)

-   Ch1: Average, unit level, conditional average treatment effects
-   Ch3: Average treatment effects on the treated

------------------------------------------------------------------------

# Estimation

Madhur Behl (2020), **Principles of Modeling for Cyber-Physical Systems**

-   [Lecture 8: Non-linear parameter estimation - part 1](https://www.youtube.com/watch?v=X-vgLZmtZV0&list=PL868twsx7OjeewCLEd-wcWnM63mOwqgTr&index=9&ab_channel=MadhurBehl)

-   [Lecture 9: Non-linear parameter estimation - part 2](https://www.youtube.com/watch?v=6U2LFQkdKWk&list=PL868twsx7OjeewCLEd-wcWnM63mOwqgTr&index=10&ab_channel=MadhurBehl)

# Optimisation, system, control

Madhur Behl (2020), **Principles of Modeling for Cyber-Physical Systems**

-   [Lecture 2: State-space modelling](https://www.youtube.com/watch?v=WvBYRkkpEa0&list=PL868twsx7OjeewCLEd-wcWnM63mOwqgTr&index=4&ab_channel=MadhurBehl)
